/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infoq.telas;
import br.com.infoq.dal.ModuloConexao;
import static br.com.infoq.telas.TelaPrincipal.desktop;
import java.awt.Color;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Grazi
 */
public class frmLogin extends javax.swing.JFrame {
        Connection conexao = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        public void logar(){
            String sql = "select * from tbusuarios where login = ? and senha = ? ";
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txt_usuario.getText());
                pst.setString(2, txt_senha.getText());
                
                //executar a query - consulta
                rs = pst.executeQuery();
                
                if(rs.next()){
                    String perfil = rs.getString(6);
                    if (perfil.equals("admin")) {
                        TelaPrincipal principal = new TelaPrincipal();
                        principal.setVisible(true);
                        TelaPrincipal.menuCadUsu.setEnabled(true);
                        TelaMenu menu = new TelaMenu();
                        desktop.add(menu);
                        menu.setVisible(true);
                        TelaMenu.btn_usuarios.setEnabled(true);
                        TelaPrincipal.lblUsuario.setText(rs.getString(2));
                        TelaPrincipal.lblUsuario.setForeground(Color.blue);
                        this.dispose();
                        conexao.close();
                    }else{
                         TelaPrincipal principal = new TelaPrincipal();
                         principal.setVisible(true);  
                         TelaPrincipal.lblUsuario.setText(rs.getString(2));
                         TelaMenu menu = new TelaMenu();
                         desktop.add(menu);
                         menu.setVisible(true);
                         this.dispose();
                         conexao.close();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Usuário ou Senha inválido");
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        ImageIcon icone = new ImageIcon("ico/user.png");
        setIconImage(icone.getImage());
        conexao = ModuloConexao.conector();
        System.out.println(conexao);
        if(conexao != null){
            lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoq/icones/dbok.png")));
        }else{
            lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoq/icones/dberro.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();
        lb_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(185, 113, 330, 40);
        getContentPane().add(txt_senha);
        txt_senha.setBounds(185, 180, 330, 40);

        btn_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoq/icones/cadeado icone 40x40.png"))); // NOI18N
        btn_login.setText("Login");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.setOpaque(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login);
        btn_login.setBounds(303, 233, 210, 50);

        lblstatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(248, 248, 248));
        lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infoq/icones/dberro.png"))); // NOI18N
        getContentPane().add(lblstatus);
        lblstatus.setBounds(10, 20, 50, 40);

        lb_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infoq/img/login.jpg"))); // NOI18N
        lb_fundo.setMinimumSize(new java.awt.Dimension(450, 230));
        lb_fundo.setPreferredSize(new java.awt.Dimension(450, 230));
        getContentPane().add(lb_fundo);
        lb_fundo.setBounds(0, 0, 530, 310);

        setSize(new java.awt.Dimension(535, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        logar();
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel lb_fundo;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
